name: ABM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mesa=3.3.0
  - python=3.12.11
  - r-base=4.5.1
  - networkx=3.5
  - pytest-mock
  - pandas=2.3.2
  - pytest-cov
  - typing
  - hypothesis
  - bandit
  - pytest-html
  - safety
  - isort
  - numpy=2.3.3
  - dataclasses
  - pytest-xdist
  - pytest
  - conda-forge::python-dotenv
  - mypy
  - faker
  - flake8
  - black
  - pytest-benchmark
  - coverage
  - matplotlib
  - seaborn
